# Generated by Django 3.0.7 on 2020-07-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20200725_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='totalAmount',
            field=models.IntegerField(),
        ),
    ]
