# Generated by Django 3.0.7 on 2020-07-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20200725_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='mob1',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='mob2',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='prdname',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ordereditems',
            name='zipCode',
            field=models.CharField(max_length=10),
        ),
    ]
