# Generated by Django 3.0.7 on 2020-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20200725_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditems',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
