# Generated by Django 3.0.7 on 2020-07-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20200725_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prdimage',
            field=models.CharField(max_length=100),
        ),
    ]
